---
project:
  description: Amazon::Lambda::Runtime::Builder
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm-module: Amazon::Lambda::Runtime::Builder
min-perl-version: 5.010
dependencies:
  requires: requires
  test-requires: test-requires
path:
  pm-module: lib
  exe-files: bin
  tests: t
extra-files:
  - ChangeLog
  - share:
      - README.md
      - share/Dockerfile
      - share/MANIFEST.json
      - share/Handler.pm.tmpl
      - share/SQS.pm.tmpl
      - share/SNS.pm.tmpl
      - share/S3.pm.tmpl
      - share/ALB.pm.tmpl
      - share/EventBridge.pm.tmpl
      - share/Makefile.mk
      - share/Makefile.builder
      - share/alb.mk
      - share/log-group.mk
      - share/overlay.mk
      - share/platform.mk
      - share/builder.stub
      - share/builder.mk
      - share/lambda-mapping.yml
      - share/ecr-create-repo.mk
      - share/eventbridge.mk
      - share/payload-sns.json
      - share/payload-s3-sqs.json
      - share/payload-eventbridge.json
      - share/payload-s3-direct.json
      - share/payload-alb.json
      - share/payload.json
      - share/policies.json
      - share/help.mk
      - share/s3.mk
      - share/sns.mk
      - share/sqs.mk
      - share/streaming.mk
      - share/lambda-alb.yaml.tmpl
      - share/lambda-eventbridge.yaml.tmpl
      - share/lambda-s3-direct.yaml.tmpl
      - share/lambda-sns.yaml.tmpl
      - share/lambda-s3-sqs.yaml.tmpl
resources:
  bugtracker:
    mailto: rclauer@gmail.com
    web: https://github.com/rlauer6/Amazon-Lambda-Runtime-Builder/issues
  homepage: https://github.com/rlauer6/Amazon-Lambda-Runtime-Builder
  repository:
    type: git
    url: git@github.com:rlauer6/Amazon-Lambda-Runtime-Builder.git
    web: https://github.com/rlauer6/Amazon-Lambda-Runtime-Builder
