#-*- mode: makefile; -*-
# Makefile.builder - generated by `alr-builder install`, safe to regenerate

FRAMEWORK_DIR := $(shell perl -MFile::ShareDir=dist_dir -e 'print dist_dir("Amazon-Lambda-Runtime-Builder")')
include $(FRAMEWORK_DIR)/Makefile.mk
