#-*- mode: makefile; -*-
# Makefile.builder - generated by `alr-builder install`, safe to regenerate, safe to commit
FRAMEWORK_DIR := $(shell perl -MFile::ShareDir=dist_dir -e 'print dist_dir("Amazon-Lambda-Runtime-Builder")' 2>/dev/null)

ifeq ($(FRAMEWORK_DIR),)
  $(error Amazon::Lambda::Runtime::Builder is not installed - run: cpanm Amazon::Lambda::Runtime::Builder)
endif

include $(FRAMEWORK_DIR)/Makefile.mk
